version: 2.1

orbs:  
  python: circleci/python@0.3.2

jobs:  
  build-and-test:
    executor:
      name: python/default
      tag: '3.7'
    steps:
      - checkout
      - run:
          name: Setup Virtual env
          command: |            
            virtualenv -p python3.7 env            
            source ./env/bin/activate
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Test
          command: python -m pytest
      - run:
          name: Package Dependencies
          command: pip install --target ./package -r requirements.txt
      - run:
          name: Create Zipfile archive of Dependencies
          command: |
            cd ./package
            zip -r9 ../function.zip .
      - run:
          name: Add App to Zipfile
          command: zip -g ./function.zip -r app
    
workflows:  
  build-test-and-deploy:    
    jobs:      
      - build-and-test:
          filters:            
            branches:
              only:
                - cicd-test-1
