version: 2.1

orbs:  
  python: circleci/python@0.3.2

jobs:  
  my-job-one:    
    executor:
      name: python/default
      tag: 3.7
    steps:
      - checkout
      - run:
          name: Setup Virtual env
          command: |            
            virtualenv -p python3.7 env            
            source env/bin/activate
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Package Dependencies
          command: pip install --target ./package -r requirements.txt
      - run:
          name: Test
          command: python -m pytest
    
workflows:  
  my-workflow-name:    
    jobs:      
      - my-job-one:
          filters:            
            branches:
              only:
                - cicd-test-1
