version: 2.1

orbs:  
  python: circleci/python@0.3.2

# references:
#   workspace_root: &workspace_root
#     /tmp/workspace
#   attach_workspace: &attach_workspace
#     attach_workspace:
#       at: *workspace_root

jobs:  
  build-and-test:
    executor:
      name: python/default
      tag: '3.7'
    steps:
      - checkout
      # - save_cache:
      #     key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      #     paths:
      #       - ~/serverless-fastapi-demo
      - run:
          name: Setup Virtual env
          command: |            
            virtualenv -p python3.7 env            
            source ./env/bin/activate
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Test
          command: python -m pytest
      # - run:
      #     name: Package Dependencies
      #     command: pip install --target ./package -r requirements.txt
      - run:
          name: Create Zipfile archive of Dependencies
          command: |
            cd env/lib/python3.7/site-packages
            zip -r9 ../../../../function.zip .
      - run:
          name: Add App to Zipfile
          command: zip -g ./function.zip -r app
      - persist_to_workspace: # store the built files into the workspace for other jobs.
          root: .
          paths:
            - .
      - run:
          name: "Persist Python assets" # Move our Zipped Lambda into our workspace.
          command: |
            set -exu
            mkdir -p /tmp/workspace/lambda
            mv function.zip /tmp/workspace/lambda/

    
workflows:  
  build-test-and-deploy:    
    jobs:      
      - build-and-test:
          filters:            
            branches:
              only:
                - cicd-test-1
