version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: '3.8'
    steps:
      - checkout
      - run:
          name: Setup Virtual Env
          command: |
            virtualenv -p python3.8 venv
            echo "source ./venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependecies
          command: pip install -r requirements.txt

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - cicd-devo-dev